// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://narqqdnaagjjjddaktun.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5hcnFxZG5hYWdqampkZGFrdHVuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2MTg1NzEsImV4cCI6MjA3MTE5NDU3MX0.R7_j6z9VW9VfQjKzLJCKfPa-9IoqMedrVBGs9xUJqnk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});